// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE41ljBqRKHa_UK-2lEvyNl7kmtbcaNZs',
    appId: '1:240691315012:web:44a68b2b713a4ac48cd711',
    messagingSenderId: '240691315012',
    projectId: 'medit-editsh',
    authDomain: 'medit-editsh.firebaseapp.com',
    storageBucket: 'medit-editsh.appspot.com',
    measurementId: 'G-CM1GZWVTYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_4oIji7jM1v3WSAR_Ik8v36zX9fWUOQ',
    appId: '1:240691315012:android:e3b9eadbd6a7f3c18cd711',
    messagingSenderId: '240691315012',
    projectId: 'medit-editsh',
    storageBucket: 'medit-editsh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWS1KWXnSdFqBPMzcNy95JqUTZqd6OeJ0',
    appId: '1:240691315012:ios:c2055a7aa592f0298cd711',
    messagingSenderId: '240691315012',
    projectId: 'medit-editsh',
    storageBucket: 'medit-editsh.appspot.com',
    iosBundleId: 'com.example.meditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhHFFUTtALEhz_8yRzxtzB7HWSWSk2Vc',
    appId: '1:774477330892:ios:1cc23a293065eba7b38569',
    messagingSenderId: '774477330892',
    projectId: 'medit-a440f',
    storageBucket: 'medit-a440f.appspot.com',
    iosBundleId: 'com.example.meditApp',
  );
}